base:
  project: auto_ml_dvc_pipeline
  random_state: 42
  target_col: price
  test_size: 0.2

data_source:
    s3_source: https://bikedata.s3.ap-south-1.amazonaws.com/dataset/Housing.csv

artifacts:
    artifacts_dir: artifacts
    raw_local_data_dir: artifacts/raw_local_data_dir
    raw_local_data: artifacts/raw_local_data_dir/data.csv

       